<?php
declare(strict_types=1);

namespace pvinvestment\classes\Domain;

final class CalculationResult
{
    public function __construct(
        public readonly float $pvRevenue,
        public readonly float $pvOperatingCosts,
        public readonly float $investorBatteryRevenue,
        public readonly float $operatorBatteryRevenue,
        public readonly float $investorBatteryCosts,
        public readonly float $operatorBatteryCosts,
        public readonly float $annualInterest,
        public readonly float $annualRepayment,
        public readonly float $annualTaxPayment,
        public readonly float $annualInvestorCashflow,
        public readonly float $savingsPlanStartingCapital,
        public readonly float $savingsPlanFixedContribution,
        public readonly float $savingsPlanCashflowContribution,
        public readonly float $savingsPlanEndingCapital,
        public readonly float $batteryGrossRevenue = 0.0,
        public readonly float $batteryNetRevenue = 0.0,
        public readonly float $batteryNetMargin = 0.0,
        public readonly float $investorBatteryCapex = 0.0,
        public readonly float $operatorBatteryCapex = 0.0,
        public readonly string $batterySharingBase = RevenueSharingModel::SHARING_BASE_GROSS_REVENUE,
        public readonly float $taxableIncome = 0.0,
        public readonly float $taxAmount = 0.0,
        public readonly int $taxPaymentYear = 0,
        public readonly float $cashflowTaxPayment = 0.0,
        public readonly float $deductibleInterest = 0.0,
        public readonly float $capitalizableAcquisitionCosts = 0.0,
        public readonly float $immediatelyDeductibleCosts = 0.0,
        public readonly float $iabDeduction = 0.0,
        public readonly float $iabAddition = 0.0,
        public readonly float $iabAcquisitionCostReduction = 0.0,
        public readonly float $depreciationBasis = 0.0,
        public readonly float $regularDepreciation = 0.0,
        public readonly float $specialDepreciation = 0.0,
        public readonly int $calculationYear = 0,
        public readonly int $investmentYear = 0,
        public readonly int $investmentMonth = 0,
        public readonly int $depreciationStartYear = 0,
        public readonly int $depreciationStartMonth = 0,
        public readonly int $eegCommissioningYear = 0,
        public readonly int $eegCommissioningMonth = 0,
        public readonly int $gridConnectionYear = 0,
        public readonly int $gridConnectionMonth = 0,
        public readonly int $revenueStartYear = 0,
        public readonly int $revenueStartMonth = 0,
        public readonly int $interestStartYear = 0,
        public readonly int $interestStartMonth = 0,
        public readonly int $repaymentStartYear = 0,
        public readonly int $repaymentStartMonth = 0,
        public readonly int $savingsPlanContributionStartYear = 0,
        public readonly int $savingsPlanContributionStartMonth = 0,
        public readonly float $revenueMonthFactor = 1.0,
        public readonly float $interestMonthFactor = 1.0,
        public readonly float $repaymentMonthFactor = 1.0,
        public readonly float $savingsPlanContributionMonthFactor = 1.0,
    ) {}

    /**
     * @return array<string, float|string>
     */
    public function toArray(): array
    {
        return [
            'pvRevenue' => $this->pvRevenue,
            'pvOperatingCosts' => $this->pvOperatingCosts,
            'investorBatteryRevenue' => $this->investorBatteryRevenue,
            'operatorBatteryRevenue' => $this->operatorBatteryRevenue,
            'investorBatteryCosts' => $this->investorBatteryCosts,
            'operatorBatteryCosts' => $this->operatorBatteryCosts,
            'batteryGrossRevenue' => $this->batteryGrossRevenue,
            'batteryNetRevenue' => $this->batteryNetRevenue,
            'batteryNetMargin' => $this->batteryNetMargin,
            'investorBatteryCapex' => $this->investorBatteryCapex,
            'operatorBatteryCapex' => $this->operatorBatteryCapex,
            'batterySharingBase' => $this->batterySharingBase,
            'annualInterest' => $this->annualInterest,
            'annualRepayment' => $this->annualRepayment,
            'annualTaxPayment' => $this->annualTaxPayment,
            'taxableIncome' => $this->taxableIncome,
            'taxAmount' => $this->taxAmount,
            'taxPaymentYear' => (float)$this->taxPaymentYear,
            'cashflowTaxPayment' => $this->cashflowTaxPayment,
            'deductibleInterest' => $this->deductibleInterest,
            'capitalizableAcquisitionCosts' => $this->capitalizableAcquisitionCosts,
            'immediatelyDeductibleCosts' => $this->immediatelyDeductibleCosts,
            'iabDeduction' => $this->iabDeduction,
            'iabAddition' => $this->iabAddition,
            'iabAcquisitionCostReduction' => $this->iabAcquisitionCostReduction,
            'depreciationBasis' => $this->depreciationBasis,
            'regularDepreciation' => $this->regularDepreciation,
            'specialDepreciation' => $this->specialDepreciation,
            'calculationYear' => (float)$this->calculationYear,
            'investmentYear' => (float)$this->investmentYear,
            'investmentMonth' => (float)$this->investmentMonth,
            'depreciationStartYear' => (float)$this->depreciationStartYear,
            'depreciationStartMonth' => (float)$this->depreciationStartMonth,
            'eegCommissioningYear' => (float)$this->eegCommissioningYear,
            'eegCommissioningMonth' => (float)$this->eegCommissioningMonth,
            'gridConnectionYear' => (float)$this->gridConnectionYear,
            'gridConnectionMonth' => (float)$this->gridConnectionMonth,
            'revenueStartYear' => (float)$this->revenueStartYear,
            'revenueStartMonth' => (float)$this->revenueStartMonth,
            'interestStartYear' => (float)$this->interestStartYear,
            'interestStartMonth' => (float)$this->interestStartMonth,
            'repaymentStartYear' => (float)$this->repaymentStartYear,
            'repaymentStartMonth' => (float)$this->repaymentStartMonth,
            'savingsPlanContributionStartYear' => (float)$this->savingsPlanContributionStartYear,
            'savingsPlanContributionStartMonth' => (float)$this->savingsPlanContributionStartMonth,
            'revenueMonthFactor' => $this->revenueMonthFactor,
            'interestMonthFactor' => $this->interestMonthFactor,
            'repaymentMonthFactor' => $this->repaymentMonthFactor,
            'savingsPlanContributionMonthFactor' => $this->savingsPlanContributionMonthFactor,
            'annualInvestorCashflow' => $this->annualInvestorCashflow,
            'savingsPlanStartingCapital' => $this->savingsPlanStartingCapital,
            'savingsPlanFixedContribution' => $this->savingsPlanFixedContribution,
            'savingsPlanCashflowContribution' => $this->savingsPlanCashflowContribution,
            'savingsPlanEndingCapital' => $this->savingsPlanEndingCapital,
        ];
    }
}
